### PR TITLE
Added the avatars section

### PR DESCRIPTION
**Pull request by Mahima-2404**
https://github.com/user-attachments/assets/21f7e553-fbcd-456b-a77f-9968124b1fb2

I've added the avatars section and also updated the navbar and footer.
Please suggest if any changes are required.
#154

### CODE REVIEW

**Comment by vishal02527** [comment]
@Mahima-2404 have you added this avatar button to all the available navbar? Is this new page responsive across all the devices?

**Comment by Mahima-2404** [comment]
@vishal02527 Working on it

**Comment by vishal02527** [comment]
@Mahima-2404 can you please attach a demo video in which you are showing its responsiveness?

**Comment by Mahima-2404** [comment]
https://github.com/user-attachments/assets/5cc86e9d-2858-46e9-8045-07239bb22e22

@vishal02527

**Pull request merged**
