### PR TITLE
Make translate to hindi button on avatars page done ! #726 #741

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Make translate to hindi button on avatars page done ! #741 #726 

Screenshot 2024-11-09 190254
Screenshot 2024-11-09 190305

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@vishal02527 done please merge my PR with Level 3 and gssoc-ext label

**Comment by Subhajit-2023-44** [comment]
@vishal02527

**Comment by vishal02527** [comment]
@Subhajit-2023-44 please resolve conflicting files issues.

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 please resolve conflicting files issues.

@vishal02527 done

**Comment by Subhajit-2023-44** [comment]
@vishal02527 level 2 😭😭

**Comment by Subhajit-2023-44** [comment]
@vishal02527 sir kindly add level 3 😭😭 I also did it twice just for you.. #741 #746

**Pull request merged**
