### PR TITLE
#79 Add create post feature to the real-time

### PR DESCRIPTION
**Pull request by Dev-Rishav**
**### Description:** 

This PR implements the backend functionality, including the creation of posts and real-time post fetching features, all integrated with the database.

**### What I've Done:**

1. Initialized the backend with Node.js, Express, and MongoDB.
2. Created a MongoDB collection to store post content.
3. Developed API endpoints to store and fetch data from the database.
4. Implemented logic to statically bind an admin message to the post array, ensuring it always appears at the top.

https://github.com/user-attachments/assets/1c520f83-2dc6-4d46-ac35-f3a991ab4a1d

### CODE REVIEW

**Comment by vishal02527** [comment]
@Dev-Rishav Great work. Before merging it, I've some questions:-

1. Are signup/login forms also connected to backend?
2. Are Logout/Delete buttons functionalities also connected to backend?
3. After merging this PR, will users be able to see their posts in real time?
4. Initially, you might have added your mongodb database, But later If I add my database account so what all things do I need to remember?

**Comment by Dev-Rishav** [comment]
@vishal02527  Thank you 

1. No, user authentication is not implemented. Its using local storage to user data.
2.  No, these are not connected to backend as of now.
3. Yes they can see their post in real time.
4. You need to deploy the database to MongoDB Atlas and then configure the .env file. The server script does not contain any static variables; all variables are ensured to use environment variables.

Let me know if you'd like any other revisions!

**Comment by vishal02527** [comment]
@Dev-Rishav If I get signup/login and logout/delete work done by another contributors, so will it impact the post creation functionality that you made?

**Comment by Dev-Rishav** [comment]
> @Dev-Rishav If I get signup/login and logout/delete work done by another contributors, so will it impact the post creation functionality that you made?

Absolutely not. User authentication will be maintained on another collection.

**Comment by Dev-Rishav** [comment]
> @Dev-Rishav Also attach a demo video for showing post creation feature on different tabs. It will make me sure if it is working on real time.

Sure, here you go!
https://github.com/user-attachments/assets/5375ee6b-3f8c-47b8-aff7-7cc51a26d635

**Comment by vishal02527** [comment]
@Dev-Rishav Thank you for your contribution! It looks like there are some merge conflicts between your changes and the current version of the repository. Could you please resolve these conflicts so that I can proceed with the review?

**Comment by Dev-Rishav** [comment]
@vishal02527  You can merge the PR,  Thank you

**Comment by vishal02527** [comment]
@Dev-Rishav Already merged. I think still I want some changes on discussion forum. for this, I will create some new issues tomorrow, you can comment there if you wish to contribute.

**Comment by Dev-Rishav** [comment]
> @Dev-Rishav Already merged. I think still I want some changes on discussion forum. for this, I will create some new issues tomorrow, you can comment there if you wish to contribute.

I would love to contribute!
 However, user authentication is a core feature that is currently missing. I am creating a new issue for it, in case you'd like this feature to be implemented. [link](https://github.com/vishal02527/My-Strength-Shree-Krishna/issues/118#issue-2564946319)

**Comment by Dev-Rishav** [comment]
> @Dev-Rishav I'm facing an huge issue after merging your PR. I'm getting 404: page not found error. Please resolve this.
> 
> Screenshot_2024-10-04-01-58-29-44

that's issue with vercel, I am looking into it.

**Comment by Dev-Rishav** [comment]
@vishal02527 Cherrypick **[this](https://github.com/Dev-Rishav/My-Strength-Shree-Krishna/commit/b0bb9acce0d6ff91c0048305ebc37b49260cd668)** commit, this will configure vercel automatically. You also need to initialize env variable too with mongo DB hosted on atlas for DB operations to be functional.

**Review by MastanSayyad — COMMENTED** [review]
That's awesome

**Pull request merged**
