### PR TITLE
Added detailed learning html pages for Srimad Bhagavatam, Bhagavad Gita & Mahabharat 

### PR DESCRIPTION
**Pull request by ananyag309**
close issue #12 

with respect to pr #139

### CODE REVIEW

**Comment by ananyag309** [comment]
@vishal02527 please have a check

**Comment by vishal02527** [comment]
@ananyag309 Paste complete demo video of website

**Comment by ananyag309** [comment]
@vishal02527 here it is

https://github.com/user-attachments/assets/dcf65dac-0847-43c5-a4df-8042f5ec13cd

(sorry for a bit low quality video)

**Comment by vishal02527** [comment]
@ananyag309 send a screenshot of gallery once.

**Comment by ananyag309** [comment]
@vishal02527 
image

**Comment by ananyag309** [comment]
@vishal02527 did i shared the correct ss cuz i currently have two folder of this repo?

**Comment by vishal02527** [comment]
@ananyag309 Although gallery is not updated in your repo but still I merge your PR. Thankyou for your contribution.

**Comment by ananyag309** [comment]
thank you

**Pull request merged**
