### PR TITLE
Navbar adjustment for small screens

### PR DESCRIPTION
**Pull request by srishti023**
#358 

Hello @vishal02527,

I have successfully resolved the issue with the navbar visibility on the Devotional Resources page. I have also visited each page individually to ensure that wherever this problem occurred, it has now been addressed.

Additionally, I made some modifications to the Mantra page, which was previously not responsive. Due to this, the navbar was not aligning properly, but that issue has also been fixed.

Please review the changes, and if everything looks good, kindly merge them. If any further adjustments are required, feel free to let me know.

Best regards,

BEFORE:

Screenshot 2024-10-12 102210

AFTER:

Screenshot 2024-10-13 142741

Mantra page before:

https://github.com/user-attachments/assets/c2f92bc5-fed4-4b5e-baed-a11b4e229621

Mantra page after:

https://github.com/user-attachments/assets/f0687e36-606d-4376-94cd-2d2478978a81

Working:

Uploading Shree Krishna_ My Strength - Google Chrome 2024-10-13 14-46-36.mp4…

### CODE REVIEW

**Comment by srishti023** [comment]
hey @vishal02527 please merge my commit as i have resolved #358 where i raised issue for navbar adjustment in every page of the website .

**Comment by vishal02527** [comment]
@srishti023 actually navbar has been changed so I request you to do changes according to latest version of repo. 
Don't worry I will add level3 for you.

**Comment by srishti023** [comment]
Subject: Request for Guidance on Implementing Hamburger Menu Functionality

Hi @vishal02527 ,

I appreciate your prompt response! I've noticed on the website regarding the navigation menu. As more options have been added, the size of the nav section has increased, which can make the site less user-friendly.

Screenshot 2024-10-21 033735

To enhance usability, I would like to implement a hamburger menu functionality. This would allow the menu to be hidden by default and only displayed when clicked, making the site more streamlined and user-friendly.

May I proceed with this implementation? I would also appreciate any guidance you could share to help me with this.

Thank you for your support!

Best regards,

**Comment by aslams2020** [comment]
This PR has been merged by the GSSoC team 
here - https://github.com/sanjay-kv/Open-source-Practice/pull/1415


 **Don't add labels to it now.**
You'll get the points in the leaderboard update.

**Pull request closed without merging**
