### PR TITLE
Updated the prasadam page

### PR DESCRIPTION
**Pull request by DevROHIT11**
I was assigned to issue #703 to enhance and update the prasadam page and I succesfully completed it !!
 Key changes  made  :- 
1. added the navbar 
2. added footer 
3. added chatbot 
4. added retrun to top arrow 
5. made the entire page responsive 
6. enhace the cards 
7. added hover effect to card 
8. change the Ui of the page 

Video :- 

https://github.com/user-attachments/assets/2ffafb4a-5a2e-4a96-a700-a49ba04c32c6

Lots of efforts require to work on this issue but finally i completed it 
@vishal02527 please accept my PR ASAP

### CODE REVIEW

**Comment by DevROHIT11** [comment]
@vishal02527 if their is another issue to work on please feel free to assign it to me !!

**Comment by vishal02527** [comment]
@DevROHIT11 it's really good. Yes definitely there is one more issue you can create it and I will assign you. The issue is related to this prasadam page only. Now there are many recipie cards but they do don't have recipes content. So you have to create a feature when user clicks on any card a dialogue box should be popped up in the middle of the screen and it shows the proper recipe of that particular card with that food image. You can give any button on card, after clicking on that button the dialogue box should be opened. Also give close icon to close the dialogue box. It should be responsive properly and good in designs and layouts.

**Comment by DevROHIT11** [comment]
Okay I will create new issue but i have some questions :- 
1. have to create the popup for every card ? 
2. the reciepe material will be provide by you or I have to add it  ?

**Comment by vishal02527** [comment]
@DevROHIT11 

1. You can take only single dialogue box but content can be dynamic so that whatever card user will click on it will show only that content.
2. Yes you have to write your own content.

**Pull request merged**
