### PR TITLE
Dark theme issue#237

### PR DESCRIPTION
**Pull request by KrishnaMohanty08**
as Mentioned in the issue created the toggle buttons in every necessary and created the function for it

### CODE REVIEW

**Comment by KrishnaMohanty08** [comment]
i the codes i resolved was not a part the this issue but error was visible in my code how ?could you elaborate

**Comment by KrishnaMohanty08** [comment]
@vishal02527 @Web-Dev-Learner can you merge this PR

**Comment by vishal02527** [comment]
@KrishnaMohanty08 attach a demo video

**Comment by vishal02527** [comment]
@KrishnaMohanty08 show me the content or card part also in dark mode.

**Comment by KrishnaMohanty08** [comment]
> @KrishnaMohanty08 show me the content or card part also in dark mode.

https://github.com/vishal02527/My-Strength-Shree-Krishna/pull/495 brother pardon i have closed this PR and made another one u can merge that one 
i will be attaching the vedio there

**Pull request closed without merging**
