### PR TITLE
feature: Dark theme added

### PR DESCRIPTION
**Pull request by ghost**
I have added Dark theme feature in your website. 
dark-theme
light-theme

Kindly review the code and if there is any changes required let me Know.
I will be happy to contribute in your project.
Thank You

### CODE REVIEW

**Comment by vishal02527** [comment]
@Vanshika2103 please provide me a proper demo video so that I can check if it is functioning for whole the website.

**Comment by Vanshika2103** [comment]
https://github.com/user-attachments/assets/0bb0ec2b-b395-48ec-9919-5d6625f1f376

This is the video of website demo.
Kindly review and acknowledge me.

Thank You.

**Comment by vishal02527** [comment]
@Vanshika2103 you added dark mode only for the body, not for the other elements. Cards are still looking white. And signup/login forms are also having white background.

**Comment by vishal02527** [comment]
Since it's been a long time and you didn't fix the issue so I had to close this PR.

**Pull request closed without merging**
