### PR TITLE
Sloka feature #62

### PR DESCRIPTION
**Pull request by aditiverma-21**
I have added the sloka section with attractive styles. please check.

### CODE REVIEW

**Comment by aditiverma-21** [comment]
@vishal02527 can you please check the PR?

**Comment by vishal02527** [comment]
@aditiverma-21 Please attach demo video of the feature here. Every time of reloading the page a new shlok should be visible on the home page according to your narration.

**Comment by aditiverma-21** [comment]
Yes sure I'll share the video

**Comment by aditiverma-21** [comment]
image
image
some screenshots

**Comment by aditiverma-21** [comment]
https://github.com/user-attachments/assets/71f7f3dc-e250-40e6-9397-4bd13e1e3a23

a demo video of feature

**Comment by aditiverma-21** [comment]
@vishal02527 can you please add tags and levels to this PR?

**Comment by aditiverma-21** [comment]
Thank You!

**Pull request merged**
