### PR TITLE
Changed the VIEW of MAIN PAGE

### PR DESCRIPTION
**Pull request by PatelHarsh2006**
Changed the VIEW of MAIN PAGE

BEFORE : 
Screenshot 2024-11-07 141457

AFTER : 
Screenshot 2024-11-07 164119

### CODE REVIEW

**Comment by PatelHarsh2006** [comment]
@vishal02527 Please review My Changes and Merge it by Assigning Labels to it !!!

**Comment by PatelHarsh2006** [comment]
@vishal02527 The Image is not responsive bcz when I tried to make it, the image was getting scretched making it not good loooking one !

**Comment by vishal02527** [comment]
@PatelHarsh2006 What width and height have you written in media query code for responsiveness?

**Comment by vishal02527** [comment]
@PatelHarsh2006 I noticed that you did not write code for making this image responsive so how it would be responsive.

**Pull request closed without merging**
