### PR TITLE
Added detailed learning html pages for Srimad Bhagavatam, Bhagavad Gita & Mahabharat

### PR DESCRIPTION
**Pull request by ananyag309**
#12 
Added detailed learning html pages for Srimad Bhagavatam, Bhagavad Gita & Mahabharat

https://github.com/user-attachments/assets/84d3805a-c116-400a-894f-8045459a3b43

qwerty
qwert

Radhe Radhe !!!

### CODE REVIEW

**Comment by vishal02527** [comment]
@ananyag309 Please use the same color and fonts for this. Also enable translator button between Hindi and English.

**Comment by ananyag309** [comment]
yes sure will be updating it soon

**Comment by vishal02527** [comment]
@ananyag309 Attach a complete demo video here to show all the changes.

**Comment by ananyag309** [comment]
@vishal02527 
https://github.com/user-attachments/assets/18ecbe8c-728e-41a3-bdb0-d477908156b8

changed all pages added hindi and english version.

its a request if it is possible can you increase the level

**Comment by ananyag309** [comment]
page 1
image
image

**Comment by ananyag309** [comment]
page 2 
image
image

**Comment by ananyag309** [comment]
@vishal02527 attached video as well please merge it

**Comment by vishal02527** [comment]
@ananyag309 Can you please paste picture of top navigation bar over here?

**Comment by ananyag309** [comment]
@vishal02527 do you want this bar 
image

i can do so but don't you think if user open it from scripture they should go back to that bage only as these pages are of secondary use only for those user who want detailed learning

**Comment by ananyag309** [comment]
@vishal02527 can you please check once as i have synced the repo the actually agter sync repo i didn't clone it to local storage beacuase changes need to be done only in those 3 html files which makes no difference as it was present in my local storage only

**Comment by vishal02527** [comment]
@ananyag309 Paste complete demo video of website

**Pull request closed without merging**
