### PR TITLE
solved #115 

### PR DESCRIPTION
**Pull request by Siddhant432**
Pls check if you are able to merge or  not. If it is ok then pls assign me this task under gssoc @vishal02527

### CODE REVIEW

**Comment by Siddhant432** [comment]
@vishal02527 now you try to merge I have resolved the conflicts and sorry for such problem

**Comment by Siddhant432** [comment]
see 

https://github.com/user-attachments/assets/5450b906-7e22-40f7-9b0e-30ad244d084b

**Comment by vishal02527** [comment]
@Siddhant432 I noticed that you made these changes in an older version of repo, but repo has been changed now so please complete your task in a latest version. For working as per new version of repo, you have to unfork the repo and delete from your local, and then again fork it and start to work.

**Comment by Siddhant432** [comment]
Ok @vishal02527

**Pull request closed without merging**
