### PR TITLE
button enhancement Master

### LINKED ISSUE #64: the style of sign in button can be improved to more elegant.
i would like to change the style of sign in button to make it more elegant.
kindly add gssoc extd label and hactoberfest label

### PR DESCRIPTION
**Pull request by Codewithmeowmeow**
enhanced button style to match with aesthetic of website.
Fixes #64
Kindly  assign appropriate labels . 
please merge.

### CODE REVIEW

**Comment by vishal02527** [comment]
@Codewithmeowmeow Please attach related screenshot of your work over here.

**Comment by Codewithmeowmeow** [comment]
@vishal02527 kindly acknowledge

This is the original
I would like to enhance it to

**Comment by Codewithmeowmeow** [comment]
> @Codewithmeowmeow Please attach related screenshot of your work over here.

hey @vishal02527  i have added screenshot kindly merge.

**Comment by Codewithmeowmeow** [comment]
Kindly merge it:)

**Comment by Codewithmeowmeow** [comment]
> @Codewithmeowmeow Please attach related screenshot of your work over here.

please merge. and label it as gssoc extended

**Comment by Codewithmeowmeow** [comment]
@vishal02527  can u please merge it and label it as under gssoc extended

**Comment by Codewithmeowmeow** [comment]
@vishal02527  despite multiple reminders you are not merging my pull request. please merge before today.

**Pull request closed without merging**
