### PR TITLE
Dark mode functionality added and styled footer

### PR DESCRIPTION
**Pull request by T-Fathima**
Added toggle button. PR: #274 
https://github.com/user-attachments/assets/2bee020c-d737-442c-b81c-f62fd71eea9a

Also done my another assigned pr
Styled the navbar section #273 
image

Please review and merge under gssoc-ext and hacktoberfest along with levels.

### CODE REVIEW

**Comment by vishal02527** [comment]
@T-Fathima Please make the changes according to latest version of repo because it has some conflicting file issues.

**Comment by T-Fathima** [comment]
> @T-Fathima Please make the changes according to latest version of repo because it has some conflicting file issues.

Resolved all the conflicts sir.
@vishal02527 Please review and merge now.

**Comment by T-Fathima** [comment]
> @T-Fathima Please make the changes according to latest version of repo because it has some conflicting file issues.

Resolved all the conflicts sir.
@vishal02527 Can u Please review and merge now under gssoc-ext level2 and hacktoberfest.

**Comment by vishal02527** [comment]
@T-Fathima Can you please attach a demo video over here so I can compare all the changes?

**Comment by T-Fathima** [comment]
https://github.com/user-attachments/assets/a79a5064-97ff-4bde-abd1-45f4ebbe9266

**Comment by vishal02527** [comment]
@T-Fathima I noticed that you made these changes in an older version of repo, but repo has been changed now so please complete your task in a latest version. Also the dark mode functionality is not as per my expectation because in it only background is changing and nothing else.

**Comment by vishal02527** [comment]
@T-Fathima For working as per new version of repo, you have to unfork the repo and delete from your local, and then again fork it and start to work.

**Comment by vishal02527** [comment]
@T-Fathima since you couldn't be able to make changes in this PR so I am closing this issue.

**Pull request closed without merging**
