### PR TITLE
Improve navbar position 

### PR DESCRIPTION
**Pull request by Web-Dev-Learner**
#7  changes,  can u added a specific level for this (nav - added 2 section , aboutus, contactus, footer)

#7 , #56, #95

- can u add the level for appropriate changes- i made  (nav - added 2 section , aboutus, contactus, footer)

Could you please add the level , "Hacktoberfest-accepted" label   to the issue .

This will ensure my contributions are counted towards Hacktoberfest.

### changes made 

Moved the About Us button to be positioned just before the Scriptures button.

Moved the Contact Us button to be positioned just after the Devotional Resources button.

###screenshots 

Screenshot 2024-10-03 111154

Screenshot 2024-10-03 111202

### CODE REVIEW

**Comment by Web-Dev-Learner** [comment]
I hope this message finds you well. I wanted to let you know that I have completed my part of the project and have resolved the issues and conflicts I encountered. If you could kindly merge my changes, I would greatly appreciate it.

### scrrenshots 


Screenshot 2024-10-09 120731

**Comment by Web-Dev-Learner** [comment]
- I have completed the work related to the navbar section.

- can you please add label for level appropriate work , gssoc-ext , hackberfest-accepted

- All checks have passed successfully.
- There are no conflicts with the base branch.

 - Could you please review and approve the workflow, and merge the PR and label.

**Comment by Web-Dev-Learner** [comment]
i have checked that from my side there is no issues  and no conflicts
I have completed the work contactus , aboutus , footer section (navbar) + content

can you please add label for level appropriate work , gssoc-ext , hackberfest-accepted

All checks have passed successfully.

There are no conflicts with the base branch.

Could you please review and approve the workflow, and merge the PR and label.

https://github.com/vishal02527/My-Strength-Shree-Krishna/pull/95/

### screenshots


Screenshot 2024-10-10 073700

**Comment by Web-Dev-Learner** [comment]
- i have completed the task , there is no conflicts .
-  can u merge and add the label.
 - Could you please add the 'level' label for this PR? In this update, I created two new navigation sections for 'Contact Us' and 'About Us' with appropriate content and updated the footer.

### label
- level
-  gssoc-ext
-  hacktoberfest-accepted

**Comment by aslams2020** [comment]
This PR has been merged by the GSSoC team 
here - https://github.com/sanjay-kv/Open-source-Practice/pull/1351

 Don't add labels to it now.You'll get the points in the leaderboard update.

**Pull request closed without merging**
