### PR TITLE
Updated Bhagwat_gita and mahabharat_detail pages with some related images.

### LINKED ISSUE #686: Adding the image of Shree Krishna with Arjun
I want to add the image of Shree Krishna with Arjun in the Bhagwat gita details.
@vishal02527 Please assign this issue to me.

### PR DESCRIPTION
**Pull request by Sakshi-maulekhi**
This fixes #686.

https://github.com/user-attachments/assets/e01fccd4-b7fd-4a2d-88f7-a995dedc3de2

https://github.com/user-attachments/assets/6542f811-c452-4f45-8d88-45a9dda332e1

https://github.com/user-attachments/assets/78f19598-8228-4798-8ed8-c473afb9cb7f

### CODE REVIEW

**Comment by vishal02527** [comment]
@Sakshi-maulekhi please attach demo video.

**Comment by Sakshi-maulekhi** [comment]
Demo video of the pictures that I put in the code with Shlokas ??

**Comment by vishal02527** [comment]
@Sakshi-maulekhi yes you have to attach demo video of  the website after doing your changes.

**Comment by Sakshi-maulekhi** [comment]
I have attached the video please check it @vishal02527 .

**Comment by vishal02527** [comment]
@Sakshi-maulekhi it is looking so simple. Can't you show these images in an efficient and attractive manner?

**Comment by Sakshi-maulekhi** [comment]
Actually,I am just a beginner so i can't able do more than this.

**Comment by vishal02527** [comment]
@Sakshi-maulekhi Okay. What about Shreemadbhagwat page? Did you not add images on this page. Please add images in this too then let me know I will merge your PR.

**Comment by Sakshi-maulekhi** [comment]
@vishal02527 Done.

**Pull request merged**
