### PR TITLE
logo updated

### PR DESCRIPTION
**Pull request by INam1995**
image
Logo updated on homepage (screenshot is after changes)
#issue 87

### CODE REVIEW

**Comment by vishal02527** [comment]
@INam1995 is it updated for all the pages?

**Comment by INam1995** [comment]
> @INam1995 is it updated for all the pages?

No it's only for main page(home page )bcz after going any other page it may possible that we have to go on home page again so we can directly go with home button that's why I have not changed on other pages

**Comment by vishal02527** [comment]
Since it's been a long time and you didn't fix the issue so I had to close this PR.

**Comment by INam1995** [comment]
@vishal02527 I have opened pull request too as per your request so why you have close this pr ?

**Pull request closed without merging**
