### PR TITLE
Added story boxes on home pages replacing the plain texts

### PR DESCRIPTION
**Pull request by durbasmriti**
I changed the story section given on the home page . I added story boxes which can be hovered on .

### CODE REVIEW

**Comment by vishal02527** [comment]
@durbasmriti please provide demo video of the web after your changes.

**Comment by durbasmriti** [comment]
https://github.com/user-attachments/assets/c367f8eb-a87b-4ce8-b7c4-c477858beae8

@vishal02527

**Comment by vishal02527** [comment]
@durbasmriti ok, I can see margin issue in the story blocks. Please fix it. There is too much margin between read less link and story.

**Comment by durbasmriti** [comment]
https://github.com/user-attachments/assets/29162728-5a30-4986-9f5b-a0aadcc7fea7

I have reduced the margin in both top and bottom side of the story content. @vishal02527 look at it once.

**Comment by vishal02527** [comment]
@durbasmriti what about translator button?

**Comment by vishal02527** [comment]
Since it's been a long time and you didn't fix the issue so I had to close this PR.

**Pull request closed without merging**
