### PR TITLE
Modify homepage, add temple page, festival page, story page and life page of shree krishna

### PR DESCRIPTION
**Pull request by anmolbajpai**
Issues no. - #526
I resolve this issue.

Homepage
Our newly designed homepage features eight engaging elements that bring the essence of Krishna's legacy to life. From interactive timelines to multimedia galleries, this central hub invites users to explore Krishna's teachings and divine pastimes.

Temples Page
The Krishna Temples page showcases stunning temples dedicated to Lord Krishna, complete with their histories and architectural highlights. Each entry includes locations with maps, guiding users to these sacred spaces and sharing the rituals and events celebrated there.

Festival Page
Explore the joyous world of Krishna's festivals on our Festivals page. Learn about celebrations like Janmashtami and Holi, with insights into their significance, rituals, and unique regional variations, all brought to life with vibrant visuals and stories.

Stories Page
Immerse yourself in enchanting tales of Lord Krishna on our Stories page. This collection of short stories highlights Krishna's divine leelas and moral teachings, designed to captivate readers and inspire devotion across all ages.

Life Page
Discover the Life of Shree Krishna through key events and teachings on our Life page. Each segment offers insights into Krishna's journey, from his miraculous birth to his role in the Mahabharata, enriching users’ understanding of his character and relevance today.

Screenshot 2024-10-21 163829
Screenshot 2024-10-21 163747
Screenshot 2024-10-21 163731
Screenshot 2024-10-21 163718
Screenshot 2024-10-21 163704
Screenshot 2024-10-21 163651
Screenshot 2024-10-21 163636
Screenshot 2024-10-21 163620
Screenshot 2024-10-21 132210

### CODE REVIEW

**Comment by vishal02527** [comment]
@anmolbajpai I liked your creativity. Please make changes according to latest version of repo because there are some conflicting issues. Also make sure the design should be responsive across all the devices. Don't forget to attach demo video after completing the work.

**Comment by vishal02527** [comment]
@anmolbajpai Hey Anmol! I have one task for you, if you want to do then please inform me here.

**Comment by anmolbajpai** [comment]
Dear Vishal

I hope you are doing well. I apologize for the delayed response, as I have
been busy with academic commitments and preparing for my upcoming exams.

It’s great to hear that you appreciate my work. I'm genuinely excited to
contribute further to the "My-Strength-Shree-Krishna" project and look
forward to making a meaningful impact.

Due to my exams, I won’t be able to dedicate time immediately. However, I
am eager to resume work in a few days and will give my best effort.

Thank you for your understanding and support.

Best regards,
Anmol Bajpai

**Comment by anmolbajpai** [comment]
Dear Vishal,

I hope you are doing well. I apologize for the delayed response, as I have
been busy with academic commitments and preparing for my upcoming exams.

It’s great to hear that you appreciate my work. I'm genuinely excited to
contribute further to the "My-Strength-Shree-Krishna" project and look
forward to making a meaningful impact.

Due to my exams, I won’t be able to dedicate time immediately. However, I
am eager to resume work in a few days and will give my best effort.

Thank you for your understanding and support.

Best regards,
Anmol Bajpai

**Comment by vishal02527** [comment]
@anmolbajpai Oh it's alright Anmol. Best wishes for your exams.

**Pull request closed without merging**
