### PR TITLE
Added faq section to home page

### PR DESCRIPTION
**Pull request by govindumeesala**
Fixes issue #75 
Added faq section to home page above footer

### CODE REVIEW

**Comment by vishal02527** [comment]
@govindumeesala Attach screenshot or demo video here.

**Comment by govindumeesala** [comment]
image
image
Heyy @vishal02527  I added screenshots

**Comment by vishal02527** [comment]
@govindumeesala Good work. Is it responsive too?

**Comment by govindumeesala** [comment]
@vishal02527 Yes it is responsive
image

**Comment by vishal02527** [comment]
@govindumeesala okay cool. Can you please add two more questions then I will merge it.

**Comment by govindumeesala** [comment]
Heyy @vishal02527  added two more faqs to it. Please check once and consider merging this pr
image

**Comment by govindumeesala** [comment]
@vishal02527  Can you please check once and consider merging this pr

**Comment by vishal02527** [comment]
@govindumeesala Thank you for your contribution! It looks like there are some merge conflicts between your changes and the current version of the repository. Could you please resolve these conflicts so that I can proceed with the review?

**Comment by govindumeesala** [comment]
@vishal02527 Heyy I resolved the conflicts, check once

**Comment by vishal02527** [comment]
@govindumeesala Now you can complete your task in the latest version of repo.

**Comment by govindumeesala** [comment]
> @govindumeesala Now you can complete your task in the latest version of repo.

ok

**Comment by govindumeesala** [comment]
> @govindumeesala Now you can complete your task in the latest version of repo.

Added feature to the newer version check one 
@vishal02527

**Comment by govindumeesala** [comment]
@vishal02527 hey please consider merging this pr 
Or if you want me to raise a new pr then i will raise a new pr.
It means a lot to me. If you merge this 

Thankyou

**Comment by vishal02527** [comment]
@govindumeesala it has still some conflicting issues. Yes you can work in latest repo and then create PR again.

**Comment by govindumeesala** [comment]
@vishal02527  Heyy I added the feature to the new version of repo .
Here is the pr #202 
Kindly close this pr and merge that one if everything is fine.

Thank you

**Pull request closed without merging**
