### PR TITLE
enhanced chatbot user interface and layout and  extended chatbot to all pages

### PR DESCRIPTION
**Pull request by DivyaJyothi9**
In the latest update, we have significantly improved the chatbot user interface to provide users with a more engaging and intuitive experience.

Screenshot (335)
Screenshot (336)

### CODE REVIEW

**Comment by DivyaJyothi9** [comment]
@vishal02527 Sir, I have created pull request for issue #429.
Have enhanced chatbot user interface and layout and extended chatbot to all pages.

I request you to kindly upgrade the level to 2 atleast ,as it has involved 2 issues to be resolved and integrated.
Kindly add the assignee and labels while merging.
Thank you so much @vishal02527!!

**Comment by DivyaJyothi9** [comment]
@vishal02527 sir, kindly merge this issue soon so that it doesn't conflict with other issues!!

**I request you to kindly upgrade the level to 2 atleast ,as it has involved 2 issues to be resolved and integrated.**
Kindly add the assignee and labels while merging.
Thank you so much @vishal02527!!

**Comment by vishal02527** [comment]
@DivyaJyothi9 Can you please again raise this PR?

**Comment by DivyaJyothi9** [comment]
Sure @vishal02527

**Comment by DivyaJyothi9** [comment]
@vishal02527 sir,raised the pr #509[enhanced chatbot user interface and layout and extended chatbot to all pages #443](https://github.com/vishal02527/My-Strength-Shree-Krishna/pull/509#top)
#509

**Pull request merged**
