### PR TITLE
Adding frame to photos to improve the appearance of photos. #290 

### PR DESCRIPTION
**Pull request by Sudhish23**
I have added the frames in gallery.

### CODE REVIEW

**Comment by vishal02527** [comment]
@Sudhish23 please attach demo video over here.

**Comment by Sudhish23** [comment]
Uploading Video (2).mp4…

**Comment by Sudhish23** [comment]
https://github.com/user-attachments/assets/e9edd355-4dd9-4213-b0bf-f81c39328c08

**Comment by vishal02527** [comment]
@Sudhish23 On clicking any image, is it showing that image in big screen as before?

**Comment by Sudhish23** [comment]
yes

**Pull request merged**
