### PR TITLE
contact us page

### PR DESCRIPTION
**Pull request by rutikakengal**
#371 issue fixed @vishal02527 
Add gssoc-ext, hactoberfast-accepted and level to this PR , This contact us page matches the homepage theme and looking good.
Screenrecording

https://github.com/user-attachments/assets/95e2f4b5-0f02-4870-bc4f-c1d2d4f4db1a

### CODE REVIEW

**Comment by vishal02527** [comment]
@rutikakengal also show its responsiveness in the video

**Comment by rutikakengal** [comment]
video for responsiveness 

https://github.com/user-attachments/assets/0d012e1b-a408-461b-a8d1-7de16cade952
Done👍@vishal02527

**Comment by vishal02527** [comment]
@rutikakengal show responsiveness on mobile devices.

**Comment by rutikakengal** [comment]
> @rutikakengal show responsiveness on mobile devices.

This is fully responsive to all devices and i resolved conflicts also @vishal02527

**Comment by rutikakengal** [comment]
Conflicts Resolved and please reveiw it @vishal02527

**Comment by vishal02527** [comment]
@rutikakengal please attach a demo video.

**Comment by rutikakengal** [comment]
Uploading Screen Recording 2024-10-28 114606.mp4…

**Comment by vishal02527** [comment]
@rutikakengal please make your changes in latest version of repo. You have implemented this feature few days ago but now website has been updated. So make changes according to it.

**Pull request closed without merging**
