### PR TITLE
Scrollup button updated Issue #31 #117

### PR DESCRIPTION
**Pull request by ShrishtiSingh26**
Closes: Issue #31 #117 
Title: add scroll to top button
Your Name: Shrishti Singh
Idenitfy yourself: Contributor in gssoc-ext and Hacktoberfest
Describe the add-ons or changes you've made 📃
Give a clear description of what have you added or modifications made
I have added the "scroll to top" button to the application to the remaining pages as well now.

Screenshot 2024-10-04 022115
Screenshot 2024-10-04 022058

### CODE REVIEW

**Comment by ShrishtiSingh26** [comment]
@vishal02527 please add the gssoc-ext labels to this

**Comment by ShrishtiSingh26** [comment]
@vishal02527 could you please add gssoc-ext labels to this PR because otherwise it won't be considered for the leader board
Thank you!

**Comment by ShrishtiSingh26** [comment]
@vishal02527 could you add gssoc-ext labels and levels to this PR because otherwise I won't get the points


Thank you!

**Comment by MastanSayyad** [comment]
@ShrishtiSingh26 added level 1 as already given level 2 previous PR which was similar to this 

image

**Pull request merged**
