### PR TITLE
Improved About Us and Contact Us sections

### PR DESCRIPTION
**Pull request by Web-Dev-Learner**
## Description
This pull request introduces new sections in the navbar for "Contact Us" and "About Us". 

### Related Issues
-  #7 
- - can u add the level for appropriate changes- i made  (nav - added 2 section , aboutus, contactus, footer)
-  can u added a specific level for this (nav - added 2 section , aboutus, contactus) 
- ref
- #7 , #56, #95
Could you please add the level , "Hacktoberfest-accepted" label and "gssoc-ext" label to the issue .

This will ensure my contributions are counted towards Hacktoberfest.

---

### Changes Made
- i have create a contactus and aboutus section in navigation with link

  **About Us Section**: 
  - Added a welcome message: "Welcome to Our Spiritual Hub".
  - added some details
  
 ---

**Contact Us Section**: 

  - Implemented a contact form with validation for required fields, ensuring the use of valid Gmail addresses.
  - A popup notification is displayed when the message is sent successfully.

---

### Screenshots

Screenshot 2024-10-02 164759

Screenshot 2024-10-02 164807

Screenshot 2024-10-02 164816

Screenshot 2024-10-02 164823

Screenshot 2024-10-02 164845

Screenshot 2024-10-02 164857

Screenshot 2024-10-02 164902

### CODE REVIEW

**Comment by vishal02527** [comment]
@Web-Dev-Learner Great! Can you please do a little change? Put About us button just before the Scriptures button and put Contact us button just after the Devotional resources button.

**Comment by Web-Dev-Learner** [comment]
###labels
#7  changes, can u added a specific level for this (nav - added 2 section , aboutus, contactus)

i have submitted another pr, i solved the nav position .
link - https://github.com/vishal02527/My-Strength-Shree-Krishna/pull/95
### changes made
Moved the About Us button to be positioned just before the Scriptures button.

Moved the Contact Us button to be positioned just after the Devotional Resources button.

**Comment by Web-Dev-Learner** [comment]
> @Web-Dev-Learner If you are able to connect this contact form to the backend then please create an issue for this. I will assign it to you.

Sure! I'll try my best.

**Comment by Web-Dev-Learner** [comment]
I hope this message finds you well. I wanted to let you know that I have completed my part of the project and have resolved the issues and conflicts I encountered. If you could kindly merge my changes, I would greatly appreciate it.

### scrrenshots 

Screenshot 2024-10-09 120741

**Comment by Web-Dev-Learner** [comment]
- I have completed the work related to theaboutus and contactus section.

- can you please add label for level appropriate work , gssoc-ext , hackberfest-accepted

- All checks have passed successfully.
- There are no conflicts with the base branch.

 - Could you please review and approve the workflow, and merge the PR and label.

**Comment by vishal02527** [comment]
@Web-Dev-Learner Are you able to fix the conflicting files issues? Or do you want me to close this PR?

**Comment by Web-Dev-Learner** [comment]
i have checked that from my side there is no issues and no conflicts
I have completed the work contactus , aboutus , footer section (navbar) + content

can you please add label for level appropriate work , gssoc-ext , hackberfest-accepted

All checks have passed successfully.

There are no conflicts with the base branch.

Could you please review and approve the workflow, and merge the PR and label.

https://github.com/vishal02527/My-Strength-Shree-Krishna/pull/56/

https://github.com/vishal02527/My-Strength-Shree-Krishna/pull/95

### screenshots



Screenshot 2024-10-10 074708

**Comment by Web-Dev-Learner** [comment]
Thank you for merging the pull request! . Could you please add the 'level' label for this PR? In this update, I created two new navigation sections for 'Contact Us' and 'About Us' with appropriate content and updated the footer.

### label
- level
-  gssoc-ext
-  hacktoberfest-accepted

**Pull request merged**
