### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by rupeshv2121**
Resolve Issues which is raised--
1. centered the Shree Krishna Image. 
2. Give border-radius where needed in landing page. 
3.Reduce size of social media icons where hovering.
4. Remove underline from read more anchor tag ang give font size when hovering.

### CODE REVIEW

**Comment by rupeshv2121** [comment]
@vishal02527 Sir pls Check and add labels gssoc-ext , hacktoberfest-accepted

**Comment by rupeshv2121** [comment]
@vishal02527  Sir why you close the PR

**Comment by vishal02527** [comment]
@rupeshv2121 resolve conflicting issues and attach demo video after completing the work.

**Comment by rupeshv2121** [comment]
@vishal02527 sir pls see and add labels

**Comment by vishal02527** [comment]
@rupeshv2121 attach demo video

**Comment by rupeshv2121** [comment]
@vishal02527 

https://github.com/user-attachments/assets/49f0dce5-8308-42aa-b2b5-8289d60dd41d

**Comment by rupeshv2121** [comment]
@vishal02527 sir pls tell why you close pr

**Comment by rupeshv2121** [comment]
@vishal02527

**Comment by vishal02527** [comment]
@rupeshv2121 these changes have already been made so I closed this PR. No longer want this to be done.

**Comment by aslams2020** [comment]
Hi, @vishal02527 
Can you please consider **Re-Reviewing it?** 
I think the issue he was assigned to is not Fully-Resolved yet. 

In the original website - 
1. The image in the hero section is **still not centered** 
image

2. the hovering effects are **still Large.**
image

In the preview demo @rupeshv2121 has provided, we can see these issues are resolved fully. 

Correct me if I'm wrong -- I'm just reviewing it so that it'll not affect the contributor's efforts.
@vishal02527 


Best Regards,
Aslam
Core team, GSSoC Extd.

**Comment by vishal02527** [comment]
@aslams2020 yes you're right. please adjust it across all devices so that it is responsive for each device.

**Comment by rupeshv2121** [comment]
@vishal02527 sir the task which i assigned i resolve

**Comment by rupeshv2121** [comment]
currently i am busy with my schedule. Pls understand me

**Comment by rupeshv2121** [comment]
@vishal02527 Sir pls merge this PR

**Comment by aslams2020** [comment]
@vishal02527 This issue was assigned to @rupeshv2121. Also Above i verified the changes he made for the task he was assigned. 
**Please unassign me here as i am not a contributor but a core team member.** 

Assign @rupeshv2121 And merge the PR. 
The work for the responsiveness of the website can be done by creating separate PR by other contributor. Atleast Rupesh should get the points for the work he did.

Please consider the request @vishal02527 ! Thanks

**Comment by vishal02527** [comment]
@rupeshv2121 I merged your PR and then seen a huge distortion in my website so I am unassigning you and removing level from this PR.

Screenshot 2024-11-02 111838

**Comment by rupeshv2121** [comment]
@vishal02527 sir core team member review my PR he is not telling any issue

**Pull request merged**
