### PR TITLE
Issue #10

### PR DESCRIPTION
**Pull request by Sapta-Dev27**
Issue #10 solved

### CODE REVIEW

**Comment by Sapta-Dev27** [comment]
@vishal02527 I have resolved the conflicts ...The conflicts were regarding to the liveserver port settings ,

**Comment by vishal02527** [comment]
@Sapta-Dev27 Can you please attach related screenshot of your task over here?

**Comment by Sapta-Dev27** [comment]
image


Yeah Sure !! @vishal02527

**Comment by Sapta-Dev27** [comment]
@vishal02527 I made sent u the SS and solved the conflicts ...I would be grateful if u kindly merge it

**Comment by Sapta-Dev27** [comment]
@vishal02527 kindly merge it

**Comment by Sapta-Dev27** [comment]
@vishal02527 Kindly merge my PR

**Comment by vishal02527** [comment]
@Sapta-Dev27 Thank you for your contribution! It looks like there are some merge conflicts between your changes and the current version of the repository. Could you please resolve these conflicts so that I can proceed with the review?

**Comment by Sapta-Dev27** [comment]
@vishal02527 I have now solved all conflicts now ...kindly merge it

**Comment by Sapta-Dev27** [comment]
@vishal02527 kindly merge the PR ....I did so many days ago

**Comment by vishal02527** [comment]
Since it's been a long time and you didn't fix the issue so I had to close this PR.

**Pull request closed without merging**
