### PR TITLE
scroll up button added

### PR DESCRIPTION
**Pull request by ShrishtiSingh26**
Closes: Issue #31 
Title: add scroll to top button
Your Name: Shrishti Singh
Idenitfy yourself: Contributor in gssoc-ext and Hacktoberfest
Describe the add-ons or changes you've made 📃
Give a clear description of what have you added or modifications made
I have added the "scroll to top" button to the application. This feature will enhance user navigation, especially on pages with long content, allowing users to easily return to the top without manually scrolling.

Home
image
Scriptures
image
Gallery
image
Devotional resources
image
Discussion forums
image

### CODE REVIEW

**Comment by ShrishtiSingh26** [comment]
@vishal02527  ah sorry about that 
I will add it to them as well asap!

**Comment by ShrishtiSingh26** [comment]
@vishal02527 resolved the issue raised in the latest PR #119

**Comment by ShrishtiSingh26** [comment]
@vishal02527 please add the gssoc-ext labels to this
Thank you!

**Comment by ShrishtiSingh26** [comment]
@vishal02527 could you please add gssoc-ext labels to this PR because otherwise it won't be considered for the leader board
Thank you!

**Comment by ShrishtiSingh26** [comment]
@vishal02527  could you add gssoc-ext labels and levels to this PR because otherwise I won't get the points


Thank you!

**Comment by vishal02527** [comment]
@ShrishtiSingh26 Already added the levels.

**Pull request merged**
