### PR TITLE
Footer added with Quick Links in Index Scriptures Gallery Discussion Devotional Sections 

### PR DESCRIPTION
**Pull request by Abbas7120**
image
image

Added Quick Links and made all footer sections in each page responsive and connected with quick navbar links . 
Can you provide me level2 for this hard work !

### CODE REVIEW

**Comment by Abbas7120** [comment]
Even made it Mobile Responsive 
image

Hope you assign me level 2 / 3 for this with gssoc-extd & hacktober fest accepted label

**Comment by Abbas7120** [comment]
Can you assign me all other issues also which I raises !

**Comment by vishal02527** [comment]
@Abbas7120 it's not looking good because alignment is going towards left. So much vacant places are left in the footer. Please enhance its beauty.

**Comment by Abbas7120** [comment]
I will enhance it ! please don't assign to anyone

**Comment by Abbas7120** [comment]
image

Work is done ! Please merged it

**Comment by Abbas7120** [comment]
image

I hope you consider my footer section instead of this as my looks more appealing for users 
Simple , plain , straightforward footer of divine website attract user more effectively 

Take a look :  image

**Comment by Abbas7120** [comment]
Sir please add the labels of gssoc-extd level 1  there and also accept my other Issues

**Comment by vishal02527** [comment]
@Abbas7120 this level is enough for now as because there are some pages where you didn't add the footer.

**Pull request merged**
