### PR TITLE
ADDED THE NEW LOGIN PAGE AND HAMBURGER ICON FOR MOBILE SCREEN

### PR DESCRIPTION
**Pull request by HS202022**
LOGIN PAGE 
https://github.com/user-attachments/assets/40ef5ee3-f553-48bf-87f4-690cb8b35430
Hamburger icon addition
https://github.com/user-attachments/assets/d4ca4a46-9de4-4a29-87d0-aff083e0d188

### CODE REVIEW

**Comment by vishal02527** [comment]
@HS202022 First of all why did you create another page for login, website has already a login page. this page will show up, only when you logout after signing up for the discussion forum. You had to design or update the changes only in that login page. 

Please remove all the changes which are made for hamburger feature because some more nav items are supposed to be taken in the navbar then you can contribute in that feature.

**Comment by HS202022** [comment]
Okay doing it

**Comment by HS202022** [comment]
> @HS202022 First of all why did you create another page for login, website has already a login page. this page will show up, only when you logout after signing up for the discussion forum. You had to design or update the changes only in that login page. 
> 
> Please remove all the changes which are made for hamburger feature because some more nav items are supposed to be taken in the navbar then you can contribute in that feature.


So basically what I need to do is reverse all the changes that I made and improve the discussion from right?

**Comment by vishal02527** [comment]
@HS202022 Simply do one thing delete the repo from your local and unfork it from github then again fork it and start working. This time you have to design only signup and login page which are already available on the website, you don't need to create any button for this feature rather just adjust or update that code according to your own logic. You don't need to implement hamburger feature this time.

**Comment by HS202022** [comment]
> @HS202022 Simply do one thing delete the repo from your local and unfork it from github then again fork it and start working. This time you have to design only signup and login page which are already available on the website, you don't need to create any button for this feature rather just adjust or update that code according to your own logic. You don't need to implement hamburger feature this time.

okay

**Pull request closed without merging**
