### PR TITLE
Add contact us page

### PR DESCRIPTION
**Pull request by rutikakengal**
#184 fixed This contact us page follows the home page theme with navbar and footbar 
@vishal02527 fixed contact us page and add gssoc-ext,hactoberfast accepted and level to this pr 
Screenshot
Screenshot 2024-10-12 135435

### CODE REVIEW

**Comment by vishal02527** [comment]
@rutikakengal Please adjust these changes according to latest version of repo. and also give some margin for contact form because there is no margin to the navbar and footer.

**Comment by vishal02527** [comment]
@rutikakengal Are you done with your work?

**Comment by rutikakengal** [comment]
yes! I am working on it @vishal02527

**Comment by vishal02527** [comment]
@rutikakengal it is too long, I will close this PR if you are not able to do your work withing few hours.

**Pull request closed without merging**
