### PR TITLE
this pr is for issue #372 slider-added

### PR DESCRIPTION
**Pull request by HarshVardhanSalve**
Screenshot 2024-10-13 194903

### CODE REVIEW

**Comment by vishal02527** [comment]
@HarshVardhanSalve the quotes is not visible correctly. You can add some glowing effects to the sliding cards so they will give some shining. Make the quote more attractive and visible correctly.

**Comment by HarshVardhanSalve** [comment]
Is this problem arised due to images ,if yes you by yourself also change the images and if not I will try to fix.

**Comment by vishal02527** [comment]
@HarshVardhanSalve you can give better enhancement to this quote section.

**Comment by HarshVardhanSalve** [comment]
Ok I will try to add some 3D effect for that and give some blurness to that quote

**Comment by HarshVardhanSalve** [comment]
@vishal02527  i have made this kind of change in it like this, now it is looking better in it or not ?
Screenshot 2024-10-15 000318
first you approve this change and tell we then i will commit changes.
i have make font size some bigger and when the quote is to happen a blur effect will come

**Comment by vishal02527** [comment]
@HarshVardhanSalve ok looking well than previous. Where have you added this slider? Attach a proper video.

**Comment by HarshVardhanSalve** [comment]
I have added this just on the main page just below the Krishna ji image I am making the video but it is getting more than 10 mb so that's why I am unable to give you that video ,so can I finally commit the changes ?

**Comment by HarshVardhanSalve** [comment]
CAN I , FINALLY COMMIT THE CHANGES ?

**Pull request closed without merging**
