### PR TITLE
Updated Current Year in the Copyright Section #521

### PR DESCRIPTION
**Pull request by koricherlasupriya**
Name: Koricherla Supriya
GitHub ID: https://github.com/koricherlasupriya/My-Strength-Shree-Krishna
Email ID: supriyakoricherla@gmail.com

fixed issue :#521
Closes: #521 
Describe the add-ons or changes you've made 📃
I have Updated Current Year in the Copyright Section Dynamically for all the pages. please review this.

Screenshots:

Before:

Copyright year change

After:

Updated Current Year in the Copyright Section

### CODE REVIEW

**Comment by vishal02527** [comment]
@koricherlasupriya I noticed that you changed the dynamic year only for some pages while there are more pages where you had to add it too. So please change this across all pages.

**Comment by koricherlasupriya** [comment]
Okay. I will work on it.

**Comment by koricherlasupriya** [comment]
I have Updated Current Year in the Copyright Section Dynamically for all the pages. please review this.

**Comment by koricherlasupriya** [comment]
I have Updated Current Year in the Copyright Section Dynamically for all the pages. please review this.

**Comment by vishal02527** [comment]
@koricherlasupriya please resolve conflicting issues. Make changes in the latest version of repo.

**Comment by koricherlasupriya** [comment]
I have resolved conflicting issues.

**Comment by koricherlasupriya** [comment]
Please assign label such as level1


Screenshot

**Comment by koricherlasupriya** [comment]
Please assign label such as level1 to My Pull Request which I have completed.

**Pull request merged**
