### PR TITLE
adding border in serach input section

### PR DESCRIPTION
**Pull request by ak-0283**
in search input section i have added a black border

### CODE REVIEW

**Comment by vishal02527** [comment]
@ak-0283 attach demo screenshot or video.

**Comment by ak-0283** [comment]
Yhi wala mai ne changes kiya hu search box mai

**Comment by ak-0283** [comment]
also i have done changes in scroll up button section 


Screenshot 2024-10-13 144735

**Comment by ak-0283** [comment]
done changes in english to hindi button in home section

**Comment by ak-0283** [comment]
Changes in sign up h2 to h1 and in all the section inside i have added placeholder👍.


Screenshot 2024-10-13 150418

**Comment by ak-0283** [comment]
in scripture page i have done change the button section 
Screenshot 2024-10-13 145624

**Comment by ak-0283** [comment]
remove the underline given the link in the scripture page
Screenshot 2024-10-13 151602

**Comment by ak-0283** [comment]
@vishal02527

**Comment by vishal02527** [comment]
@ak-0283 border of search bar is not visible correctly.

**Comment by ak-0283** [comment]
@vishal02527 now it's 👍 ok

**Comment by ak-0283** [comment]
in the scriptures page i have added black border looks great 
@vishal02527 #512 

Screenshot 2024-10-17 223357

**Comment by ak-0283** [comment]
please review and merge it @vishal02527

**Comment by vishal02527** [comment]
@ak-0283 I no longer want this feature so I'm closing this PR.

**Pull request closed without merging**
