### PR TITLE
Changed Footer Part [Fixed #194]

### LINKED ISSUE #194: Footer Section
Your footer section is nice but i want to improve it.

### PR DESCRIPTION
**Pull request by GyanaPrakashSahoo7853**
###What does this PR do?
This PR fixes the footer part and social media icons to more aesthetics and redirecting to relevant social websites. Also added animation to each and everything.

Fixes #194 

https://github.com/user-attachments/assets/c5fa541a-72ac-45cb-9200-7e0710247066

###How should this be tested?

 - [x] Go to Footer part of website
 - [x] Hover on the social media icons
 - [x] Click on the social media icons to redirect to relevant website

### CODE REVIEW

**Comment by aslams2020** [comment]
@GyanaPrakashSahoo7853 Please resolve the Conflicts first.

then @vishal02527 will be able to merge the PR.

**Comment by GyanaPrakashSahoo7853** [comment]
> @GyanaPrakashSahoo7853 Please resolve the Conflicts first.
> 
> then @vishal02527 will be able to merge the PR.
> 

Solved the conflict please merge my PR

**Comment by aslams2020** [comment]
@vishal02527 Please go ahead.
thankyou!

**Comment by vishal02527** [comment]
@GyanaPrakashSahoo7853 I no longer want this feature in my website.

**Pull request closed without merging**
