### PR TITLE
Create auto-comment-issue.yml

### LINKED ISSUE #276: Auto Commenting On New Issue Creation
it ensures that comments on issues follow a consistent format or structure. This helps teams maintain a standardized approach to handling issues, reducing confusion and misunderstandings.
Users don’t need to manually add repetitive information or instructions. The automatic comment can include standard guidelines, troubleshooting steps, or links to documentation.

### PR DESCRIPTION
**Pull request by sejals23**
Closes #276

### CODE REVIEW

**Comment by vishal02527** [comment]
@sejals23 There are some conflicting issues.

**Comment by sejals23** [comment]
@vishal02527 Conflict Resovled

**Comment by vishal02527** [comment]
@sejals23 I don't know the significance of this auto-comment-issue.yml, can you please describe it what is this and why is it needed?

**Comment by sejals23** [comment]
Auto-commenting is a feature that automatically posts a comment when an issue is closed in a repository.
When the issue is closed, a pre-defined comment will be automatically posted, acknowledging the closure.
The action will run every time an issue is closed, without needing manual input.

Auto-comments ensure that every closed issue receives a response, maintaining a consistent communication standard.
Automating this process helps maintainers focus on coding and fixing issues, rather than manually writing a comment for every closed issue.

**Comment by vishal02527** [comment]
@sejals23 So can this feature affect my website?

**Comment by sejals23** [comment]
No, it will not effect your website. This is just to manage your repository better

**Pull request closed without merging**
