### PR TITLE
fixed mainpage image responsiveness #38

### PR DESCRIPTION
**Pull request by devarsheecodess**
I have aliigned the image perfectly along with the translate button. Below, i am attaching the screenshot of the results.
WhatsApp Image 2024-10-02 at 22 57 09_904d19d6

### CODE REVIEW

**Comment by devarsheecodess** [comment]
@vishal02527 i have fixed all the conflicts. before merging my PR, plz add gssoc-ext, hacktoberfest-accepted and level2 labels

**Comment by devarsheecodess** [comment]
@vishal02527 can you plz merge my PR? with labels

**Comment by devarsheecodess** [comment]
@vishal02527 ??

**Comment by vishal02527** [comment]
@devarsheecodess please resolve conflicting files issues.

**Comment by devarsheecodess** [comment]
@vishal02527 i have resolved them

**Comment by devarsheecodess** [comment]
@vishal02527 also add the labels here too orelse it wont count

**Comment by devarsheecodess** [comment]
@vishal02527 plz merge the PR orelse there will be merge conflicts again 🥹

**Comment by vishal02527** [comment]
@devarsheecodess I'm not able to see any changes. Sorry I no longer want this PR to be merged. You can work on different issues of this repo. Thankyou

**Comment by devarsheecodess** [comment]
I have attached a screenshot above, I had made the image responsive

**Pull request closed without merging**
