### PR TITLE
Responsive NavBar and Some Design Enhancements

### PR DESCRIPTION
**Pull request by shanvid19**
Hey @vishal02527 !

I have worked on the issue assigned to me #299 , and made few changes. I have listed them below, along with their demonstration:

1. Firstly, I enhances the navbar by increasing it's width to 100vw and by removing it's right margin, so that it appears in a proper manner in any device it is viewed in. I also removed the Home Button to bring a sense of uniformity to the design.
Screenshot 2024-10-12 011656

2. After enhancing the width of the header, i also increased the width of footer for the same reasons as well as to bring unifromity in design of the website.
Screenshot 2024-10-12 011732

3. Thirdly, I enhanced the design of the ChatBot Button. I changed it's background colour to white and to make it pop to the visitors, i added a border of 3px to it.
Screenshot 2024-10-12 011740

4. I also made a few changes in the hero section of the website. I properly aligned it to the centre so that it looks more put together
Screenshot 2024-10-12 011802

6. Next change which I made was in the structure of documentation of the code base. I created a separate css file (style.css) and made some additions to the js file, script.js for convinience of people who are gonna access it in future.

7. Lastly, I added a Hamburger Menu to the mobile version of the website.
Screenshot 2024-10-12 011820

### CODE REVIEW

**Comment by vishal02527** [comment]
@shanvid19 please attach a proper demo video here so that I can compare the changes and add suitable levels for you.

**Comment by shanvid19** [comment]
Here you go!

https://github.com/user-attachments/assets/d136bc9e-2b2d-4f4e-8c2d-55d5450a9337

**Comment by vishal02527** [comment]
@shanvid19 Are you sure this updation are made across all the available pages on the site?

**Comment by shanvid19** [comment]
> @shanvid19 Are you sure this updation are made across all the available pages on the site?

Yes. Every page has the same navbar code plus the changes i made here and there in html file, as well as, they are linked to the same css and js file.

**Comment by shanvid19** [comment]
Screen Recording 2024-10-12 215414.mp4
<https://drive.google.com/file/d/1GCwPryQ-A2Umyi5EyEbiJ5eU9z_VihMC/view?usp=drive_web>
I have added navbar to every webpage, i have demonstrated it above in this
video

**Comment by shanvid19** [comment]
Screen Recording 2024-10-12 223228.mp4
<https://drive.google.com/file/d/1sKRCdZh_kGO_I3JUQNmw4QsG6qyUgHKk/view?usp=drive_web>
Sorry, wrong attachment. This is the right one. Please view it and let me
know.

**Comment by shanvid19** [comment]
Please add the "hacktoberfest-accepted" label also

**Pull request merged**
