### PR TITLE
Stylised the signup and login.html page

### PR DESCRIPTION
**Pull request by Rishav123raj**

### CODE REVIEW

**Comment by Rishav123raj** [comment]
Stylised the login and signup page

**Comment by vishal02527** [comment]
@Rishav123raj attach screenshot or demo video.

**Comment by Rishav123raj** [comment]
Screenshot (318)
Screenshot (319)
@vishal02527 Attached the screenshot for my issue , please check it and assign me the issue,.

**Comment by vishal02527** [comment]
@Rishav123raj Good work I merged this PR.

**Pull request merged**
