### PR TITLE
Enhance Styles in prasadam.css

### PR DESCRIPTION
**Pull request by NirajD04**
**Description:**

**This PR introduces enhancements to the prasadam.css file to improve the overall aesthetic and responsiveness of the webpage. The modifications aim to retain existing styles while implementing adjustments that enhance visual appeal and usability.**

Changes Made:

Typography Improvements:

Enhanced font choices and sizes for improved readability.
Consistent spacing and alignment for headings and paragraphs.
Background and Color Adjustments:

Updated color gradients for a modern look.
Increased contrast for better visibility of text and UI elements.
Recipe Card Layout Enhancements:

Adjusted spacing and alignment of recipe cards for better presentation.
Added hover effects to improve interactivity.
Implemented a grid layout for better responsiveness.
Button Style Enhancements:

Enhanced button styles with hover effects for improved user feedback.
Ensured buttons are responsive across different screen sizes.
Responsive Design Optimization:

Tested and adjusted styles for smaller screen sizes to ensure a consistent user experience.
Optimized images for better loading times without compromising quality.
Screenshots: (Include any relevant screenshots here to showcase the visual changes.)

Testing:

The changes have been tested across various devices to ensure compatibility and responsiveness.
Related Issue:

This PR addresses issue #<issue-number> (if applicable).
Additional Notes:

All enhancements have been made without removing any existing styles, maintaining the original design intention.

### CODE REVIEW

**Comment by NirajD04** [comment]
@vishal02527  please accept this pr under gssoc'24 extd
issue #666

**Comment by vishal02527** [comment]
@NirajD04 please attach demo video and also show its responsiveness.

**Comment by NirajD04** [comment]
https://github.com/user-attachments/assets/f9c918b8-b44d-4e3a-bd6e-2802a082e0e1

Enhanced hover effects with smooth transitions and added responsive styling adjustments for better readability and interactivity across devices.  @vishal02527

**Comment by vishal02527** [comment]
@NirajD04 I don't think you done good changes in it. It is looking the same as before. You can work on its responsiveness.

**Pull request closed without merging**
