### PR TITLE
Fixed the glitch

### PR DESCRIPTION
**Pull request by Peart-Guy**
Referring to #292  pull request and issue #260 
I have solved the glitch and henceforth creating this new pull request

### CODE REVIEW

**Comment by vishal02527** [comment]
@Peart-Guy Although I merged it but problem has not been resolved yet. I can still see the same issue on mobile device.

**Comment by vishal02527** [comment]
@Peart-Guy I can't add the levels for you because I already told you that I merged the PR but still issue has not been resolved.

**Comment by Peart-Guy** [comment]
> @Peart-Guy I can't add the levels for you because I already told you that I merged the PR but still issue has not been resolved.

@vishal02527 
I solved the issue for Desktop version and the Morning mantras page is functioning properly which used to look like this
Before:
Screenshot 2024-10-09 214309
Screenshot 2024-10-09 214338

Now all the download links are working perfectly, the page is working properly and the webpage looks beautiful 
After:
image

I think all these effort deserves the gssoc-extd 24 and level and hacktober

**Comment by Peart-Guy** [comment]
@vishal02527 
 It's Day two of asking my Level and Gssoc-24. You took the work without giving the deserving Labels.
This type of behavior is not accepted. Kindly Treat this urgent

**Comment by Peart-Guy** [comment]
Hi @vishal02527 ,
This is the second day I'm following up on my Level and GSSoC-24. I believe my contributions deserve proper recognition, and I'd appreciate your prompt attention to this. Thanks!

**Comment by vishal02527** [comment]
I can't add the levels for you because I already told you that I merged the PR but still issue has not been resolved.

**Pull request merged**
