### PR TITLE
Improve preloader

### PR DESCRIPTION
**Pull request by VidhanThakur09**
Related Issue
Closes: #167 

### Description
Styling has been applied to the preloader. The preloader is present on all pages of the website with styling. For styling and loading, a CSS file is created and the JS file is updated. 

*Improvements:*

1. *Optimized Preloader:* Enhanced the preloader animation on the devotional-resources, gallery, Home, scriptures, and signup pages to improve user experience.

2. *Revamped Preloader Design:* Redesigned the preloader with modern CSS styling to enhance visual appeal.

3. *Dedicated Preloader Design:* Created a separate CSS file named` "preloaderStyle.css"` to manage the preloader functionality, ensuring better code organization and maintainability.

4. *Loading Behavior :* Updated JSs file to manage the preloader Loading, ensuring better code organization and maintainability.

## How Has This Been Tested? ⚙️

The program was tested locally on a machine using the Chrome browser. To verify the changes, the website was loaded after the modifications were made. This involved manually inspecting the visual elements and functionally testing various user interactions to ensure the changes were implemented correctly.

## Screenshots 📷

**Before changes** 

Screenshot 2024-10-07 135253

**After adding preloader**

https://github.com/user-attachments/assets/0dbde0a6-f3c7-4e5d-9f79-74dcb4c8ccd3

### CODE REVIEW

**Comment by VidhanThakur09** [comment]
@vishal02527 now fix 

issue number #167 
please merge this before someone edit the codebase
Screenshot 2024-10-10 021445

**Comment by vishal02527** [comment]
@VidhanThakur09 I can see this preloader has not been implemented for all the available pages on the site. Please make it for all the pages and also attach a demo video.

**Comment by VidhanThakur09** [comment]
https://github.com/user-attachments/assets/563ebe04-0777-4bdd-a6ea-07a4217fd594

@vishal02527 please review the attached video

**Comment by VidhanThakur09** [comment]
@vishal02527 now all the pages have PreLoader  ,please merge this before someone edit the codebase

**Comment by vishal02527** [comment]
@VidhanThakur09 please attach demo video over here.

**Comment by VidhanThakur09** [comment]
https://github.com/user-attachments/assets/5ad689ba-b660-4bb0-a820-e1f1d4d2fcec

**Comment by vishal02527** [comment]
No it's not as expected.

**Comment by VidhanThakur09** [comment]
its loading in local host thats why it is fast but in hosting it will work like mock

**Comment by VidhanThakur09** [comment]
@vishal02527 I would greatly appreciate it if you could kindly inform me of your decision at your earliest convenience. Thank you very much for your time and consideration.

**Pull request closed without merging**
