### PR TITLE
enhanced

### PR DESCRIPTION
**Pull request by Codewithmeowmeow**
#275 
https://github.com/user-attachments/assets/25ec8ae0-49c7-4005-9539-187e9e9e8ecd
please update it to level 3

### CODE REVIEW

**Comment by vishal02527** [comment]
@Codewithmeowmeow give a translator button also so that users can read the quote in Hindi too. Also modal should be responsive.

**Comment by Codewithmeowmeow** [comment]
@vishal02527 sorry to bother you but can u please explain what do u mean by being responsive?? and for translation i am working on it.

**Comment by vishal02527** [comment]
@Codewithmeowmeow Responsive means it should be best fit across all the devices like pc, tablet and mobile etc. Didn't you know this, it is very basic term in web development.

**Comment by Codewithmeowmeow** [comment]
Done

https://github.com/user-attachments/assets/2f98df73-aac5-4aba-9bdf-2c1deeb89ac9

@vishal02527 please review it

**Comment by vishal02527** [comment]
@Codewithmeowmeow I noticed one thing, on clicking translate button it is showing quote in both languages. But you can do one thing, initially quote will be loaded in english and there is button "translate to hindi", so when user clicks on "translate to hindi" button it should show the quote in hindi only and now button should be "translate to english". Did you understand my concern?

**Pull request closed without merging**
