### PR TITLE
Enhance Navigation Bar Styling

### PR DESCRIPTION
**Pull request by akshayks13**
This PR resolves the over lapping of the nav bar elements , I have given a better over lay for them
Screenshot 2024-10-30 at 6 15 24 PM

Please merge this PR

### CODE REVIEW

**Comment by akshayks13** [comment]
Please add the GSSOC and Hacktoberfest badge

**Comment by vishal02527** [comment]
@akshayks13 is it updated for all the pages. please show a demo video. Also show its responsiveness.

**Comment by akshayks13** [comment]
As of now i have only edited for the Home page , because only It had many nav bar elements 

And yes , it is Responsive

[Uploading Screen Recording 2024-10-31 at 12.08.39 PM.zip…]()


As the file size is big , I cannot upload the video directly , but provided a zip

**Comment by vishal02527** [comment]
@akshayks13 link is not accessible yet. It's showing uploading...

**Comment by akshayks13** [comment]
Please verify it now

**Pull request closed without merging**
