### PR TITLE
🚀[FEATURE] Make translate to hindi button on avatars page done ! #726

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Make translate to hindi button on avatars page done - #726

https://github.com/user-attachments/assets/93512d65-1bc2-48c8-8577-a0fd1001c251

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@vishal02527 Sir, this task really wasted a lot of time, no matter, I did it correctly.         

Sir I will be very grateful if you could give me level 3 for this.. I hope you understand me 🙁

Please check & merge my PR, Thank you 🙏🏻

**Comment by vishal02527** [comment]
@Subhajit-2023-44 please write "हिन्दी में पढ़िए" instead of "translate in Hindi".

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 please write "हिन्दी में पढ़िए" instead of "translate in Hindi".

@vishal02527 sir please see my code if i give new pr then i have to do the whole thing again its already wasting my lot of time,

sir please merge this PR then i will give new pr for it - write "हिन्दी में पढ़िए" instead of "translate in Hindi".


image

**Comment by Subhajit-2023-44** [comment]
@vishal02527

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 please write "हिन्दी में पढ़िए" instead of "translate in Hindi".

@vishal02527 done, please merge my PR

**Pull request closed without merging**
