### PR TITLE
Implemented connect logout and delete account features

### PR DESCRIPTION
**Pull request by meghanakn473**
This pull request introduces two important features to enhance user experience in the discussion forum application: Connect Logout and Delete Account. With the Connect Logout feature, users can log out without losing their posts, allowing them to easily access their contributions when they return. The Delete Account feature empowers users to permanently remove their accounts and all associated data, ensuring their privacy is respected. We've made necessary updates in auth.js to support these functionalities, and adjusted the user data schema to keep posts intact after logout, only removing them when an account is deleted. These changes aim to give users greater control over their accounts while preserving the value of their contributions to the forum.

### CODE REVIEW

**Comment by meghanakn473** [comment]
can i know if my code is merged with the main code?

**Comment by meghanakn473** [comment]
okay ill upload and attach it

**Comment by meghanakn473** [comment]
@vishal02527 can u please check the pr and allow for merge request?

**Comment by vishal02527** [comment]
@meghanakn473 I appreciate your hard work. Can you please attach demo video for this so that I can understand easily if it is working or not?

**Pull request closed without merging**
