### PR TITLE
Styled the scroll to top button with arrow up icon

### LINKED ISSUE #201: Styling the scroll to top button
@vishal02527 Presently the scroll to top button is simply a text within the button. I want to make it as an icon. 
Please assign this under gssoc-ext and hacktoberfest accepted labels.

### PR DESCRIPTION
**Pull request by Abankita**
Fixes #201 
@vishal02527  I have styled the scroll to top button. I have applied the changes in all the pages. Please review this. 

BEFORE:
Screenshot_2024-10-08-13-15-52-884~2
 
AFTER: 
Screenshot (71)_010236~3

### CODE REVIEW

**Comment by Abankita** [comment]
@vishal02527 please review this pr and assign gssoc-ext, hacktoberfest accepted and level 1 labels. 
Thank you!

**Comment by Abankita** [comment]
@vishal02527 can you please review this pr and assign gssoc-ext labels? 
Thank you!

**Comment by vishal02527** [comment]
@Abankita is it updated for all the available pages on the website?

**Comment by Abankita** [comment]
> @Abankita is it updated for all the available pages on the website?

Yes, I have updated for all the pages. @vishal02527

**Pull request merged**
