### PR TITLE
Footer change

### PR DESCRIPTION
**Pull request by Web-Dev-Learner**
### label 
#7 ,
-Additionally, I would like to request the following labels for the issue:

- can u add the level for appropriate changes- i made  (nav - added 2 section , aboutus, contactus, footer)

-level label (appropriate for the difficulty)
-Hacktoberfest-accepted label
-gssoc-ext

### reference 

https://github.com/vishal02527/My-Strength-Shree-Krishna/pull/56
https://github.com/vishal02527/My-Strength-Shree-Krishna/pull/95

### before changes 

Screenshot 2024-10-04 131215

---

### changes made

- created 2 section in nav 
-  with respective content 
- updated footer 

updated footer with link 
---
### screen shots

Screenshot 2024-10-04 131042

### CODE REVIEW

**Comment by Web-Dev-Learner** [comment]
I hope this message finds you well. I wanted to let you know that I have completed my part of the project and have resolved the issues and conflicts I encountered. If you could kindly merge my changes, I would greatly appreciate it. 


### screenshots

Screenshot 2024-10-09 120726

**Comment by Web-Dev-Learner** [comment]
- I have completed the work related to the footer section.

- can you please add label for level appropriate work , gssoc-ext , hackberfest-accepted

- All checks have passed successfully.
- There are no conflicts with the base branch.

 - Could you please review and approve the workflow, and merge the PR and label.

**Comment by vishal02527** [comment]
Since it's been a long time and you didn't fix the issue so I had to close this PR.

**Comment by Web-Dev-Learner** [comment]
i have checked that from my side there is no issues 
I have completed the work contactus , aboutus , footer section (navbar) + content

can you please add label for level appropriate work , gssoc-ext , hackberfest-accepted

All checks have passed successfully.

There are no conflicts with the base branch.

Could you please review and approve the workflow, and merge the PR and label.

https://github.com/vishal02527/My-Strength-Shree-Krishna/pull/95/

### screenshots


Screenshot 2024-10-10 073700

**Pull request closed without merging**
