### PR TITLE
ADDED THE CURSOR Animation EFFECT( INDIAN Tricolor )

### PR DESCRIPTION
**Pull request by PatelHarsh2006**
[ADDED THE CURSOR Animation EFFECT( INDIAN Tricolor )](https://github.com/vishal02527/My-Strength-Shree-Krishna/commit/5bf0d8f14ba0434c5116217857a4e43ed0177edf)

(BEFORE)

(AFTER)

https://github.com/user-attachments/assets/5056c374-b2b3-4d9e-a6db-f5e123c26f0a

### CODE REVIEW

**Comment by PatelHarsh2006** [comment]
@vishal02527 Please Review  My Newly Added FEATURE and I would be very THANKFULL to You if Possible Please ASSIGN it LEVEL-3 LABEL.

**Comment by vishal02527** [comment]
@PatelHarsh2006 is it working for all pages? If yes then please provide a quick demo video for all the pages.

**Comment by vishal02527** [comment]
@PatelHarsh2006 Please resolve conflicting file issues.

**Comment by PatelHarsh2006** [comment]
@vishal02527 Conflicts are RESOLVED !!!

**Comment by vishal02527** [comment]
@PatelHarsh2006 Although I merged this PR, but I got an issue on the site, some features have been distorted. Please do the needful changes in the latest version of repo, otherwise I will remove the levels.

Screenshot 2024-10-11 214206

**Comment by PatelHarsh2006** [comment]
> For working as per new version of repo, you have to unfork the repo and delete from your local, and then again fork it and start to work.

After that again should I request a Pull Request ?

**Comment by vishal02527** [comment]
@PatelHarsh2006 Yes you can.

**Comment by PatelHarsh2006** [comment]
@vishal02527  Sir, I think my pull request might not have been merged because I unforked and deleted from local folder and re-forked and cloned again but the cursor animation is not the part of newly cloned file !!!

**Comment by vishal02527** [comment]
@PatelHarsh2006 You should have already saved that particular code.

**Comment by PatelHarsh2006** [comment]
eb1fd1ed43bc926b1a92987a0a67550de751f000

**Pull request merged**
