### PR TITLE
Add Visitor Counter feature done ! #685 ✨✨ 

### PR DESCRIPTION
**Pull request by Subhajit-2023-44**
Hello, PR
Add new feature - #685
Add Visitor Counter feature done properly -

Screenshot 2024-11-02 004223

Before -

image

### CODE REVIEW

**Comment by Subhajit-2023-44** [comment]
@vishal02527 Done #685 

image

Please merge my PR with label..

Thank You

**Comment by vishal02527** [comment]
@Subhajit-2023-44 Is this visitor's count according to real time?

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 Is this visitor's count according to real time?

@vishal02527 the code counts page views per user.. I have done this before on other websites, they also gave me Lev 3 for this..

Screenshot 2024-10-22 204511

Please merge my PR with label.. Thank You 🙏🏻

**Comment by Subhajit-2023-44** [comment]
@vishal02527 please add Level 3 and gssoc-ext label

**Comment by Subhajit-2023-44** [comment]
@vishal02527 sir please add Level 3 and gssoc-ext label..

Thank You

**Comment by vishal02527** [comment]
@Subhajit-2023-44 I'm having an issue regarding its responsiveness, when I'm scrolling up so it is being hidden like this:

Screenshot_2024-11-04-01-03-22-78

**Comment by vishal02527** [comment]
@Subhajit-2023-44 also tell me, is this visitors count visible to only me or is it for everyone?

**Comment by Subhajit-2023-44** [comment]
Sorry sir, I didn't get any notification of your message.. 😞

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 also tell me, is this visitors count visible to only me or is it for everyone?

For all user..

**Comment by vishal02527** [comment]
@Subhajit-2023-44 suppose if visitor count is 10 and someone visits the site from his end then it will be updated from 10 to 11 for all users. Right?

It is updating in real time or just locally?

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 I'm having an issue regarding its responsiveness, when I'm scrolling up so it is being hidden like this:
> 
> Screenshot_2024-11-04-01-03-22-78

Sir maybe this is happening because this total page is not fully responsive..,

Sir I am also a beginner, I don't know how to make a page responsive otherwise I would send assign request for it, because I really need points, I am a gssoc-ext contributor only 2 days left

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 suppose if visitor count is 10 and someone visits the site from his end then it will be updated from 10 to 11 for all users. Right?
> 
> It is updating in real time or just locally?

No sir it locally, the code counts page views per user

**Comment by Subhajit-2023-44** [comment]
> > @Subhajit-2023-44 Is this visitor's count according to real time?
> 
> @vishal02527 the code counts page views per user.. I have done this before on other websites, they also gave me Lev 3 for this..
> 
> Screenshot 2024-10-22 204511
> 
> Please merge my PR with label.. Thank You 🙏🏻

..

**Comment by Subhajit-2023-44** [comment]
@vishal02527  I have done this before on other websites, they also gave me Lev 3 for this..,

 I have done this before on other websites, they also gave me Lev 3 for this.. other top project admins prefer this visitor counter..

**Comment by Subhajit-2023-44** [comment]
you can check other projects(website's) they also prefer this visitor counter.. 

Screenshot 2024-11-07 032231
Screenshot 2024-11-07 032305
Screenshot 2024-11-07 032350
Screenshot 2024-11-07 032419
Screenshot 2024-11-07 032436
Screenshot 2024-11-07 032457
Screenshot 2024-11-07 032509
Screenshot 2024-11-07 032519

**Comment by vishal02527** [comment]
@Subhajit-2023-44 I don't think it is suitable for the website to have the count of local visits of oneself. I considered that you would implement this feature in real time but as it is made locally only so I can't give levels to you. Sorry for this time.

**Comment by Subhajit-2023-44** [comment]
> @Subhajit-2023-44 I don't think it is suitable for the website to have the count of local visits of oneself. I considered that you would implement this feature in real time but as it is made locally only so I can't give levels to you. Sorry for this time.

@vishal02527 Sir you merged my PR, Sir kindly give me at least Level 2 😭😭

**Comment by Subhajit-2023-44** [comment]
@vishal02527 Sir kindly give me at least Level 2

**Pull request merged**
