### PR TITLE
Add Mini chatbot

### PR DESCRIPTION
**Pull request by ruchikakengal**
#108 fixed 
Add mini chatbot ,add gssoc-ext,hactoberfast accepted and level 3 to this issue @vishal02527 
Screenrecording

https://github.com/user-attachments/assets/372bad76-9430-4e3c-a8d4-491f01de6b05

### CODE REVIEW

**Comment by vishal02527** [comment]
@ruchikakengal Great work. Thank you for your contribution! It looks like there are some merge conflicts between your changes and the current version of the repository. Could you please resolve these conflicts so that I can proceed with the review?

**Comment by ruchikakengal** [comment]
#218  resolved the conflicts.

**Comment by ruchikakengal** [comment]
#218  resolved the conflicts.

**Comment by vishal02527** [comment]
@ruchikakengal See these SS:

Screenshot 2024-10-11 004734

Screenshot 2024-10-11 004838

**Comment by ruchikakengal** [comment]
add hackcoberfest label to this @vishal02527

**Comment by ruchikakengal** [comment]
Add Hactoberfest accepted label to this PR @vishal02527 , As I  currently need it achive my fourth badge of hactoberfest , please

**Pull request merged**
