### PR TITLE
fixing Navbar

### PR DESCRIPTION
**Pull request by sahhoArjun097**
i  fixed the navbar and place the navbar elements properly.

https://github.com/user-attachments/assets/9c3accf0-131c-418c-8c13-c8bb48ec8a96

### CODE REVIEW

**Comment by sahhoArjun097** [comment]
can you please add the label GSSoC 2024 Extd relaevant and lvl .

**Comment by sahhoArjun097** [comment]
please check the change that i make

**Comment by sahhoArjun097** [comment]
image
 see i didn't get any point for this PR please assign me lable

**Comment by sahhoArjun097** [comment]
issue number : - #8

**Comment by aditya-bhaumik** [comment]
@vishal02527 hi can you please tell me why you are not adding the gssoc and level labels to the pull requests 

i reviewed all your  pull requests and you have not been adding labels to any of them is there any particular reason

**Comment by aditya-bhaumik** [comment]
@vishal02527 please add the labels on the all the pull requests you have merged

**Comment by sahhoArjun097** [comment]
@vishal02527 add labels

**Pull request merged**
