### PR TITLE
add ggogle login

### PR DESCRIPTION
**Pull request by amanver45**
#208 

Screenshot 2024-10-16 234452
Screenshot 2024-10-16 234505

Screenshot 2024-10-16 234518

### CODE REVIEW

**Comment by amanver45** [comment]
@vishal02527 sir pls check and merge it

**Comment by vishal02527** [comment]
@amanver45 is it functioning correctly?

**Comment by vishal02527** [comment]
@amanver45 resolve this problem:

Screenshot_2024-10-17-03-30-15-18

**Comment by amanver45** [comment]
@vishal02527 sir pls check now

**Comment by amanver45** [comment]
@vishal02527 what issue you face during login

**Comment by vishal02527** [comment]
@amanver45 I attached the screenshot, have look on that.

**Comment by amanver45** [comment]
"Sir, the Google login is working fine from my side. Please assign this issue to someone else. I have worked on this issue for more than 10 days, so please at least add a level 1 label. Thank you."

**Comment by amanver45** [comment]
@vishal02527 "Sir, the Google login is working fine from my side. Please assign this issue to someone else. I have worked on this issue for more than 10 days, so please at least add a level 1 label. Thank you."

**Pull request merged**
