### PR TITLE
Updated carousel feature index.html  for issue#44

### PR DESCRIPTION
**Pull request by aditiverma-21**
I have added the carousel feature please check

### CODE REVIEW

**Comment by vishal02527** [comment]
@aditiverma-21 Attach demo video or screenshot here.

**Comment by aditiverma-21** [comment]
Yes sure

**Comment by aditiverma-21** [comment]
image

https://github.com/user-attachments/assets/62f73ac7-bfaf-4d5a-932b-bfcab1db5f3d

pictures changes by itself and also by the arrow

**Comment by aditiverma-21** [comment]
@vishal02527 Can you please add labels and level to this PR ?

**Comment by aditiverma-21** [comment]
@vishal02527 can you please add labels and levels to this PR? Please see this. This PR is not showing int he board. can you please label????

**Comment by aditiverma-21** [comment]
Thank you!

**Pull request merged**
