### PR TITLE
logout and delete account modal added issue #247

### PR DESCRIPTION
**Pull request by AyushSharma72**
i added a modal which conforms user logout 
and delete accoutn 

image 1:
Screenshot (198)

image 2:
Screenshot (197)

**please add gssoc-ext and level1 label before merge**

### CODE REVIEW

**Comment by vishal02527** [comment]
@AyushSharma72 It has some conflicting files issue please make changes according to latest version of repo.

**Comment by AyushSharma72** [comment]
> @AyushSharma72 It has some conflicting files issue please make changes according to latest version of repo.

@vishal02527 check now

**Comment by vishal02527** [comment]
@AyushSharma72 is it responsive too?

**Comment by AyushSharma72** [comment]
> @AyushSharma72 is it responsive too?

yes

**Comment by AyushSharma72** [comment]
> > @AyushSharma72 is it responsive too?
> 
> yes it is already small width so it is responsive

hey @vishal02527  please merge this PR

**Comment by vishal02527** [comment]
@AyushSharma72 please resolve conflicting files issues. Make sure you made these changes in the latest version of repo.

**Comment by AyushSharma72** [comment]
> @AyushSharma72 please resolve conflicting files issues. Make sure you made these changes in the latest version of repo.

Hey bro if you merge the PR which are made after mine there will always be merge conflicts please merge the PR in order they are made

**Comment by AyushSharma72** [comment]
> @AyushSharma72 please resolve conflicting files issues. Make sure you made these changes in the latest version of repo.

i created another pull request check here https://github.com/vishal02527/My-Strength-Shree-Krishna/pull/384

**Pull request closed without merging**
