### PR TITLE
New features and enhancements

### PR DESCRIPTION
**Pull request by gouravi19**
**Summary of Changes:** This pull request introduces several new features and improvements to enhance user experience and functionality:

**Quiz Page**: A fully functional quiz page has been added, allowing users to engage with interactive quizzes.

**Feedback Form**: A new feedback form enables users to provide their opinions and suggestions, helping us improve the platform.

**Digital Resource Page**: This page offers a collection of digital resources, now equipped with a night mode for better accessibility during low-light conditions and a language change option to cater to a diverse audience.

**Personalized To-Do List**: The to-do list has been personalized to help users manage their tasks more effectively, ensuring a tailored experience.

**Partner Page:** A new partner page has been created to showcase our collaborators and resources, promoting better visibility and engagement.

**Additional Features:**

Implemented a night mode feature for improved usability.
Added a language change option to accommodate a wider range of users.
Testing:

All new features have been tested across different devices and browsers to ensure compatibility and functionality.
Change the logo (3)
Change the logo (4)
Change the logo (5)
Change the logo (6)
Change the logo (7)

### CODE REVIEW

**Comment by vishal02527** [comment]
@gouravi19 wow that's really great. Do a little change, whatever new feature buttons you have added in the top navigation bar, instead of making button you have to make drop-down arrow adjacent to "other resources". So whenever user will click on the drop-down arrow he can see all these features. Also make sure that this feature is implemented in all the available pages like discussion forum, stories, meerabai, surdas, morning mantras, wallpaper etc pages and it should be responsive across all the devices. Best of luck for that.

**Comment by gouravi19** [comment]
sure sir I will do it thank you for the feedback

**Comment by gouravi19** [comment]
**Dropdown Feature Added in the Navigation Bar**

Dear Sir,

I have successfully implemented the requested changes to the website. Instead of separate buttons, I have added a dropdown arrow adjacent to the "Other Resources" menu in the top navigation bar. Now, users can view all the options under this section when they click the dropdown arrow. This feature has been applied to all the available pages, including the Discussion Forum, Stories, Meerabai, Surdas, Morning Mantras, and Wallpaper sections.

Additionally, I have ensured that this feature is responsive across all devices.

Please feel free to check and let me know if any further adjustments are needed.

Change the logo (8)
Change the logo (9)
Change the logo (10)

**Comment by gouravi19** [comment]
Sir please do add hactoberfest and hactoberfest-accepted tag please sir

**Comment by gouravi19** [comment]
Above changes are for the issue #256 and the pull request created is #434

**Comment by gouravi19** [comment]
sir i have completed it you can check it #434

**Comment by vishal02527** [comment]
@gouravi19 why this page is looking different because navbar is looking different.

**Comment by gouravi19** [comment]
Sir I have made all the **navbar look** similar you can check them 
want (1)

**Comment by gouravi19** [comment]
**ITS RESPONSIVENESS ACROSS THE MOBILE DEVICES AND OTHER DEVICES TOO**

https://github.com/user-attachments/assets/b6086d50-3655-47f2-a58d-9f62a0fe2029

**I HAVE DONE ALL THE CHANGES IN THESE VIDEOS YOU CAN SEE THAT THE OTHER RESOURCES BUTTON THE LINK ITEAMS ARE VISIBLE EVEN WITHOUT HOVERING**  


https://github.com/user-attachments/assets/1ad7cd66-9bab-44f6-b991-4525785492d9

**Pull request merged**
