### PR TITLE
Added dark mode functionality to entire website

### PR DESCRIPTION
**Pull request by Ankitha2130**
Completed #310

### CODE REVIEW

**Comment by Ankitha2130** [comment]
Please review it @vishal02527

**Comment by vishal02527** [comment]
@Ankitha2130 Please attach a proper demo video  for showing this feature.

**Comment by Ankitha2130** [comment]
Uploading ShreeKrishna-my strength.mp4…

I have uploaded the video

**Comment by Ankitha2130** [comment]
https://drive.google.com/file/d/1y9299k0TZMlgCRK4YkDIDk3KYYQ17Wrr/view?usp=drive_link
Above is the video link of the dark mode functionality demo. Please review it.

**Comment by Ankitha2130** [comment]
@vishal02527 please review it.

**Comment by vishal02527** [comment]
@Ankitha2130 give me access to watch the video

**Comment by vishal02527** [comment]
@Ankitha2130 okay I watched the video. You have made these changes in the last version of repo but now repo has been changed so please do the changes according to latest version of repo.

**Comment by Ankitha2130** [comment]
Ok I will do it and send

**Comment by Ankitha2130** [comment]
https://drive.google.com/file/d/1y9299k0TZMlgCRK4YkDIDk3KYYQ17Wrr/view?usp=drive_link
I have done dark mode functionality to the updated repo. Above is the link please review it @vishal02527

**Comment by Ankitha2130** [comment]
@vishal02527 please review it

**Pull request merged**
